# -*- coding: utf-8 -*-
"""Day1_talentselection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S94sQUVx-aRzO9sRum192-oL2kJckZsz
"""

!pip install pdfplumber spacy scikit-learn
!python -m spacy download en_core_web_sm

from google.colab import files
uploaded = files.upload()

import pdfplumber

def extract_text_from_pdf(file_name):
    text = ""
    with pdfplumber.open(file_name) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text + " "
    return text

file_name = list(uploaded.keys())[0]
resume_text = extract_text_from_pdf(file_name)

print("✅ Resume Text Extracted\n")
print(resume_text[:1000])  # show first 1000 characters

skills_list = [
    "python", "java", "c++", "machine learning", "deep learning",
    "react", "node.js", "django", "flask", "sql", "mongodb",
    "html", "css", "javascript", "data analysis", "tensorflow",
    "pytorch", "excel", "accounting", "finance", "quickbooks"
]

def extract_skills(text):
    text = text.lower()
    found_skills = []

    for skill in skills_list:
        if skill in text:
            found_skills.append(skill)

    return list(set(found_skills))

resume_skills = extract_skills(resume_text)

print("\n✅ Extracted Skills:")
print(resume_skills)

job_description = """
Looking for an accounting professional with experience in financial management,
bookkeeping, SQL, auditing, and QuickBooks. Knowledge of Excel is required.
"""

def skill_based_similarity(resume_skills, jd):
    jd = jd.lower()
    match_count = 0

    for skill in resume_skills:
        if skill in jd:
            match_count += 1

    return match_count / len(resume_skills) if resume_skills else 0

score = skill_based_similarity(resume_skills, job_description)

print("✅ Improved Similarity Score:")
print(f"{round(score * 100, 2)}%")

def rank_candidate(score):
    if score > 0.7:
        return "Highly Suitable ✅"
    elif score > 0.4:
        return "Moderately Suitable ⚠️"
    else:
        return "Not Suitable ❌"

ranking = rank_candidate(score)

print("\n✅ Candidate Ranking:")
print(ranking)



