# -*- coding: utf-8 -*-
"""day3_talentselection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ThZryTNt0bxY3GzKi5uwKgRFT5Vmy3v
"""

!pip install sentence-transformers pdfplumber

import pdfplumber
import re
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from google.colab import files

uploaded = files.upload()

!pip install reportlab

from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet

def create_pdf(filename, text):
    doc = SimpleDocTemplate(filename)
    styles = getSampleStyleSheet()

    content = []
    for line in text.split("\n"):
        content.append(Paragraph(line, styles["Normal"]))

    doc.build(content)

# Resume 1 (Perfect Match)
resume1 = """John Doe

Professional Summary:
Experienced professional with 5+ years of experience in management, communication, and data handling.

Skills:
- Management
- Communication
- Excel
- Reporting

Experience:
Worked as a team leader managing operations and handling organizational tasks efficiently for over 5 years.

Education:
B.Tech in Computer Science"""
create_pdf("perfect_resume.pdf", resume1)

# Resume 2 (Irrelevant)
resume2 = """Jane Smith

Professional Summary:
Creative individual with passion for cooking, painting, and music.

Skills:
- Cooking
- Dancing
- Painting

Experience:
Worked as a freelance artist and chef.

Education:
Diploma in Fine Arts"""
create_pdf("irrelevant_resume.pdf", resume2)

from google.colab import files
files.download("perfect_resume.pdf")
files.download("irrelevant_resume.pdf")

from google.colab import files
uploaded = files.upload()

model = SentenceTransformer('all-MiniLM-L6-v2')

def extract_text_from_pdf(file_name):
    text = ""
    with pdfplumber.open(file_name) as pdf:
        for page in pdf.pages:
            text += page.extract_text() or ""
    return text

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z0-9\s.]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text

def split_sentences(text):
    sentences = re.split(r'\.', text)
    return [s.strip() for s in sentences if len(s.strip()) > 20]

skills_dict = {
    "python": ["python"],
    "machine learning": ["ml", "machine learning", "pytorch"],
    "frontend": ["react", "frontend", "javascript"],
    "database": ["sql", "mysql", "database"],
    "accounting": ["accounting", "finance", "bookkeeping"],
    "excel": ["excel"],
    "communication": ["communication"],
    "management": ["management"]
}

def extract_skills(text):
    text = text.lower()
    found_skills = []

    for skill, keywords in skills_dict.items():
        for word in keywords:
            if word in text:
                found_skills.append(skill)
                break

    return found_skills

def experience_score(text):
    matches = re.findall(r'(\d+)\s*(?:\+)?\s*years', text.lower())

    if matches:
        years = max([int(x) for x in matches])
        return min(years / 10, 1)

    if "intern" in text.lower():
        return 0.3
    elif "project" in text.lower():
        return 0.2

    return 0.1

def confidence_level(score):
    if score > 70:
        return "High"
    elif score > 50:
        return "Medium"
    else:
        return "Low"

def generate_justification(candidate):
    skills = candidate['skills']
    semantic = candidate['semantic']

    if candidate['score'] > 60:
        return f"Strong candidate with good semantic alignment ({semantic:.2f}%) and relevant skills {skills[:3]}."
    elif candidate['skill_score'] > 50:
        return f"Candidate has relevant skills {skills[:2]} but moderate semantic alignment ({semantic:.2f}%)."
    elif semantic > 45:
        return "Good contextual understanding but lacks key required skills."
    else:
        return "Low match due to weak alignment in both skills and experience."

job_description = """
Looking for a professional with experience in management, communication,
data handling, reporting, and organizational skills.
"""

results = []

jd_clean = clean_text(job_description)
jd_embedding = model.encode(jd_clean)

jd_skills = extract_skills(job_description)

for file_name in uploaded.keys():

    resume_text = extract_text_from_pdf(file_name)
    resume_clean = clean_text(resume_text)

    sentences = split_sentences(resume_clean)

    similarities = []

    for sentence in sentences:
        sent_embedding = model.encode(sentence)
        sim = cosine_similarity([sent_embedding], [jd_embedding])[0][0]
        similarities.append(sim)

    # 🔥 TOP-K SEMANTIC (UPGRADE)
    top_k = sorted(similarities, reverse=True)[:3]
    semantic = sum(top_k) / len(top_k) if top_k else 0

    skills = extract_skills(resume_text)

    # 🔥 IMPROVED SKILL SCORE
    skill_match = len(set(skills) & set(jd_skills))
    skill = skill_match / len(jd_skills) if jd_skills else 0

    experience = experience_score(resume_text)

    final_score = (
        0.5 * semantic +
        0.3 * skill +
        0.2 * experience
    )


    missing_skills = list(set(jd_skills) - set(skills))

    results.append({
        "name": file_name,
        "score": final_score * 100,
        "semantic": semantic * 100,
        "skill_score": skill * 100,
        "experience_score": experience * 100,
        "skills": skills,
        "missing_skills": missing_skills
    })

max_score = max([c["score"] for c in results])

for c in results:
    c["normalized_score"] = (c["score"] / max_score) * 100

ranked_results = sorted(results, key=lambda x: x["score"], reverse=True)

print("\n🏆 FINAL SMART TALENT RANKING:\n")

for i, candidate in enumerate(ranked_results, start=1):

    print(f"{i}. {candidate['name']}")
    print(f"   Final Score: {candidate['score']:.2f}%")
    print(f"   Normalized: {candidate['normalized_score']:.2f}%")
    print(f"   Semantic: {candidate['semantic']:.2f}%")
    print(f"   Skill: {candidate['skill_score']:.2f}%")
    print(f"   Experience: {candidate['experience_score']:.2f}%")
    print(f"   Skills: {candidate['skills']}")
    print(f"   Missing Skills: {candidate['missing_skills']}")
    print(f"   Confidence: {confidence_level(candidate['score'])}")
    print(f"   Justification: {generate_justification(candidate)}")
    print(f"   Recommendation: {'SELECT' if candidate['score'] > 50 else 'REJECT'}")

    print("-" * 50)